//SQL Reporting by Example
// https://teamtreehouse.com/library/sql-reporting-by-example

//Gets students whose last name starts with A
select * from subjects
WHERE LAST_NAME like "A%";

//Gets students whose last name starts with any letter from A to M
select * from subjects
WHERE LAST_NAME > "A" and LAST_NAME < "N"
order by LAST_NAME ASC;

//Get Capacity of schools
select sum(CAPACITY) from ROOMS;

//Which room has the highest capacity?
select id, max(CAPACITY) from ROOMS;

//What subjects are taught in that room?
select DISTINCT NAME from CLASSES
join SUBJECTS on CLASSES.SUBJECT_ID = SUBJECT.ID
WHERE ROOM_ID = 19;

//Which teachers teach only 8th grade?
with DATA as (
    SELECT DISTINCT t.ID, t.FIRST_NAME, t.LAST_NAME, s.GRADE FROM TEACHERS AS t
    JOIN CLASSES AS c ON t.ID = c.TEACHER_ID
    JOIN SUBJECTS AS s ON c.SUBJECT_ID = s.ID
)

SELECT distinct FIRST_NAME, LAST_NAME FROM DATA
WHERE GRADE = 8
AND ID NOT IN (SELECT ID FROM DATA WHERE GRADE != 8);

//Which teachers teach 7th grade science?
SELECT DISTINCT FIRST_NAME, LAST_NAME FROM SUBJECTS
JOIN CLASSES ON SUBJECTS.ID = CLASSES.SUBJECT_ID
JOIN TEACHERS ON TEACHERS.ID = CLASSES.TEACHER_ID
WHERE NAME = "Science" AND GRADE = 7;

//Which teachers teach elective subjects (no grade levels)?
SELECT DISTINCT FIRST_NAME, LAST_NAME FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE GRADE IS NULL;

//Generate a schedule for Rex Rios
SELECT PERIOD_ID, SUBJECTS.NAME, SUBJECTS.GRADE FROM STUDENTS
JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE FIRST_NAME = "Rex" AND LAST_NAME = "Rios"
ORDER BY PERIOD_ID ASC;

//How many students hav PE in first period?
SELECT COUNT(1) FROM STUDENTS
JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
WHERE PERIOD_ID = 1 AND SUBJECTS.NAME = "Physical Education";

//Prediction: If there will be around 220 6th grade students next year
//Does the school have enough capacity (check capacity of lowest room)
SELECT MIDIInput(CAPACITY) FROM CLASSES
JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
JOIN ROOMS ON ROOMS.ID = CLASSES.ROOM_ID
WHERE GRADE = 6;

//Capacity of lowest room is 30, and there are 7 periods in a day
//30 * 7 = 210, so this can accomodate for only 210 students
//The school cannot accomodate 220 students

//How many teachers teach all 7 periods?
SELECT TEACHERS.ID, FIRST_NAME,LAST_NAME, COUNT(1) FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
GROUP BY TEACHERS.ID
HAVING COUNT(1) = 7;

//Which teachers teach more than 1 subject?
SELECT TEACHERS.* FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
GROUP BY TEACHERS.ID
HAVING COUNT(DISTINCT SUBJECT_ID) > 1;

//Get teacher Janis' schedule
WITH JANIS_CLASSES AS (
    SELECT PERIOD_ID, SUBJECTS.NAME FROM TEACHERS
    JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
    JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
    WHERE TEACHERS.ID = 391
)

SELECT PERIODS.ID, JANIS_CLASSES.NAME FROM PERIODS
LEFT OUTER JOIN JANIS_CLASSES ON PERIODS.ID = PERIOD_ID;

//Which subject is the most popular and how many students are taking it?
WITH SUBJECT_COUNTS AS (
    SELECT SUBJECTS.NAME, COUNT(1) AS "CT" FROM SUBJECTS
    JOIN CLASSES ON SUBJECTS.ID = CLASSES.SUBJECT_ID
    JOIN SCHEDULE ON CLASSES.ID = SCHEDULE.CLASS_ID
    GROUP BY SUBJECT_ID
)

SELECT NAME, MIN(CT) FROM SUBJECT_COUNTS;

//Which students have 5th period science and 7th period art?
WITH FIFTH_SCIENCE AS (
    SELECT STUDENT_ID FROM STUDENTS
    JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
    JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
    JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
    WHERE PERIOD_ID = 5 AND SUBJECTS.NAME = "Science"
)

WITH SEVENTH_ART AS (
    SELECT STUDENT_ID FROM STUDENTS
    JOIN SCHEDULE ON STUDENTS.ID = SCHEDULE.STUDENT_ID
    JOIN CLASSES ON CLASSES.ID = SCHEDULE.CLASS_ID
    JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
    WHERE PERIOD_ID = 7 AND SUBJECTS.NAME = "Art"
)

SELECT C.* FROM FIFTH_SCIENCE A
JOIN SEVENTH_ART B ON A.STUDENT_ID = B.STUDENT_ID
JOIN STUDENTS C ON A.STUDENT_ID = C.ID;

//Which elective teacher teaches the most students?
WITH ELECTIVE_TEACHERS AS (
    SELECT DISTINCT FIRST_NAME, LAST_NAME FROM TEACHERS
    JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
    JOIN SUBJECTS ON SUBJECTS.ID = CLASSES.SUBJECT_ID
    WHERE GRADE IS NULL;
)

WITH STUDENT_COUNTS AS (
    SELECT ELECTIVE_TEACHERS.ID, COUNT(1) AS "CT" FROM ELECTIVE_TEACHERS
    JOIN CLASSES ON ELECTIVE_TEACHERS.ID = CLASSES.TEACHER_ID
    JOIN SCHEDULE ON CLASSES.ID = SCHEDULE.CLASS_ID
    GROUP BY ELECTIVE_TEACHERS.ID
)

SELECT MAX(STUDENT_COUNTS.CT), TEACHERS.FIRST_NAME, TEACHERS.LAST_NAME
FROM STUDENT_COUNTS
JOIN TEACHERS ON STUDENT_COUNTS.ID = TEACHERS.ID;

//Which teachers don't have a class during 1st period?
SELECT TEACHERS.* FROM TEACHERS
EXCEPT //Subtracts queries
SELECT TEACHERS.* FROM TEACHERS
JOIN CLASSES ON TEACHERS.ID = CLASSES.TEACHER_ID
WHERE PERIOD_ID = 1;